#!/bin/bash
# SL
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
# ==========================================
# Getting
MYIP=$(wget -qO- ipinfo.io/ip);
echo "Checking VPS"
IZIN=$( curl ipinfo.io/ip | grep $MYIP )
if [ $MYIP = $MYIP ]; then
echo -e "${NC}${GREEN}Permission Accepted...${NC}"
else
echo -e "${NC}${RED}Permission Denied!${NC}";
echo -e "${NC}${LIGHT}Fuck You!!"
fi
clear
echo " "
echo " "

if [ -e "/var/log/xray/access.log" ]; then
        LOG="/var/log/xray/access.log";
fi
if [ -e "/var/log/xray/error.log" ]; then
        LOG="/var/log/xray/error.log";
fi
#
if [ -f "/var/log/xray/access.log" ]; then
echo ""
anjay=$(netstat -anp | grep ESTABLISHED | grep xray | awk '{print $4}' | sort | uniq);
rm -r /tmp/anjay-login.txt
clear
echo "---------=[ XRAY Login ]=---------";
echo "XRAY |  IP Address  |  Connected";
echo "----------------------------------------------";
        netstat -anp | grep ESTABLISHED | grep xray | awk '{print $4}' | sort | uniq > /tmp/anjay-login.txt
        cat /tmp/anjay-login.txt
fi
echo "----------------------------------------------";
echo "---------=[ XRAY Info Login ]=---------";
echo "XRAY |  IP Address  |  Connected";
echo "----------------------------------------------";
        cat /var/log/xray/access.log | grep -B 4 "xray" | awk '{print $0}' | tail -n 500 | cut -d " " -f 1,2,3 | sort | uniq > /tmp/anjay-login.txt
        cat /tmp/anjay-login.txt
fi
echo "----------------------------------------------";
echo
echo "----------------------------------------------";
echo "Script MANTAPV3 By SL"
echo "";

