
#
# GETTING DOMAIN NAME
Domen="$(cat /etc/xray/domain)"
slow="$(cat /root/nsdomain)"
echo -e ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "\E[44;1;39m              ⇱ System Information ⇲             \E[0m"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "❇️ Hostname    : $HOSTNAME"
echo -e "❇️ OS Name     : $Tipe"
echo -e "❇️ Total RAM   : ${totalram}MB"
echo -e "❇️ Public IP   : $MYIP"
echo -e "❇️ Domain      : $Domen"
echo -e "❇️ NS Domain   : $slow"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "\E[44;1;39m            ⇱ Service Information ⇲             \E[0m"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "❇️ SSH OpenSSH             :$status_ssh"
echo -e "❇️ SSH Dropbear            :$status_beruangjatuh""
echo -e "❇️ SSH SlowDNS             :$status_slowdns"
echo -e "❇️ SSLH                    :$sosslh"
echo -e "❇️ SSH Stunnel5            :$status_stunnel"
echo -e "❇️ SSH Websocket TLS       :$swstls"
echo -e "❇️ SSH Websocket HTTP      :$swsdrop"
echo -e "❇️ XRAY Multi Port         :$status_xray"
echo -e "❇️ Super XRAY              :$status_super_xray"
echo -e "❇️ NGINX                   :$status_nginx"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo ""
